# vim:foldmethod=marker

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

PURE_PROMPT_SYMBOL='$'

# Plugins {{{
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

zinit ice wait'!0' silent
zinit light zsh-users/zsh-syntax-highlighting
zinit ice wait'!0' silent
zinit light zsh-users/zsh-completions
zinit ice wait'!0' silent
zinit light hlissner/zsh-autopair
zinit ice wait'!0' silent
zinit light Tarrasch/zsh-bd
zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions
# }}}

ZSH_THEME=''
source ~/.oh-my-zsh/oh-my-zsh.sh

zstyle ':prompt:pure:path' color '#A89984'
zstyle ':prompt:pure:git:*' color '#FE8019'
zstyle ':prompt:pure:git:branch' color '#FABD2F'
zstyle ':prompt:pure:prompt:success' color '#7C6F64'

alias ls='exa -F --long --octal-permissions --no-permissions --no-user'
# }}}

eval "$(direnv hook zsh)"
