#! /usr/bin/env bash
# vim:foldmethod=marker

# Immediately visible programs {{{

feh --bg-scale $HOME/Pictures/wallpapers/obra.png &
bspc monitor eDP-1 -d "1 " "2 " "3 " "4 " "5 " "6 " "7 " "8 " "9 " "0 " 
polybar laptop &

# }}}

# General bspc configuration {{{

DARK="#272727"

bspc config window_gap -2
bspc config top_padding 34
bspc config border_width 2

for state in normal focused unfocused active
do
  bspc config ${state}_border_color $DARK
done

for side in right bottom left
do
 bspc config ${side}_padding 2
done

# }}}

# Startup programs {{{

SHELL=dash sxhkd &

picom &
clipmenud &
unclutter --timeout 1 --hide-on-touch &

# }}}
