#! /bin/sh

sxhkd &
picom &
clipmenud &

bspc monitor -d "1 " "2 " "3 " "4 " "5 " "6 " "7 " "8 " "9 " "10 "

bspc config normal_border_color "#272727"
bspc config focused_border_color "#3B3736"

bspc config border_width 1
bspc config window_gap -1

for side in top right bottom left
do
 bspc config ${side}_padding 1
done

feh --bg-scale /home/jeremiah/Pictures/wallpapers/blank.jpg

polybar bar &
sleep 2
xdo below -t $(xdo id -n root) $(xdo id -a polybar-bar_eDP1)
$HOME/.pyenv/libexec/pyenv exec flashfocus
